black-desk/cgtproxy

- internal/config/config.go
- internal/config/config_test.go
- fix(config): correct context message
- fix(config): correct Tproxy.Addr validation
> black desk/fix/config test

- internal/config/alloc.go
- internal/config/check.go
- internal/config/config.go
- internal/config/config_test.go
- internal/config/error.go
- internal/config/string.go
- internal/consts/consts.go
- internal/core/rulemanager/rulemanager.go
- internal/test/gomega-helper/matcher.go
- internal/test/gomega-helper/matchers/matcherr.go
- test/data/example_config.yaml
- test/data/validation_fail.yaml
- test/data/wrong_ports.yaml
- test/data/wrong_type.yaml
- refact(config): add `proxies` and `tproxies`
- refact(config): error handling for `tproxy-ports`
- feat: add gomega-helper
- test(config): add tests
> black desk/refact/config

- cmd/deepin-network-proxy-manager/cmd/check.go
- cmd/deepin-network-proxy-manager/cmd/checkconfig.go
- cmd/deepin-network-proxy-manager/cmd/checkkernel.go
- cmd/deepin-network-proxy-manager/cmd/root.go
- internal/config/check.go
- internal/config/config_test.go
- internal/config/load.go
- internal/config/string.go
- internal/core/monitor/monitor.go
- internal/core/monitor/monitor_test.go
- internal/core/new.go
- internal/core/rulemanager/rulemanager.go
- internal/core/rulemanager/table/method.go
- internal/core/rulemanager/table/new.go
- internal/core/run.go
- internal/inject/inject_test.go
- internal/test/ginkgo-helper/table_test.go
- test(ginkgo-helper): use MatchError
- style: `if err != nil` in next line
> black desk/test/ginkgo helper

- cmd/deepin-network-proxy-manager/cmd/check.go
- cmd/deepin-network-proxy-manager/cmd/checkconfig.go
- cmd/deepin-network-proxy-manager/cmd/checkkernel.go
- cmd/deepin-network-proxy-manager/cmd/root.go
- internal/log/zap-journal/encoder/implement.go
- feat(zap-journal): AddString without quotes
- chore: add some logs
> Improve zap-journal

- internal/log/log_debug.go
> chore(log): use zap.NewDevelopment() as fallback debug logger

- Makefile
> build: strip bin

- internal/config/config.go
- internal/consts/consts.go
- fix: make tproxy-ports required
- chore: remove unused consts
> some clean up

- internal/inject/inject.go
> docs: add a todo

- Makefile
- README.md
- cmd/cgtproxy/cmd/root.go
- internal/core/table/init.go
- internal/core/table/method.go
- misc/systemd/cgtproxy.service
- docs: update README
- fix: apply KeyByteOrder to all set
- fix: add missing rules to output chain
- feat: systemd integration
> systemd integration

- internal/core/monitor/run.go
> fix: ignore unknow fsEvent error

- internal/core/table/init.go
For web service listen at local port,
the first package it receive in an connection is not go through TPROXY.
In such situation, if we redirect the reply package send from service to
TPROXY, it will somehow result in an connection closed error.
This rule is copy from cgtproy:
https://github.com/springzfx/cgproxy/blob/86fe42eccb2ad9a42955e371c849b2e160f65ab6/cgroup-tproxy.sh#L207
> fix(table): do not tproxy any "reply"

- README.md
- internal/config/config.go
- internal/core/monitor/error.go
- internal/core/table/init.go
- internal/core/table/method.go
- internal/core/table/new.go
- misc/config/example_without_repeater.yaml
- style: format
- feat: implement dns hijack
- docs: update README and godoc
> feat: dns hijack

- internal/core/table/init.go
- internal/core/table/method.go
- internal/core/table/new.go
> fix(table): add missing output nat hook chain

- README.md
- misc/config/example_without_repeater.yaml
> docs: update README

- internal/core/core.go
- internal/core/providers.go
- internal/core/run.go
- internal/core/wire.go
- internal/core/wire_gen.go
> refact: correct wire use

- misc/config/example_without_repeater.yaml
> docs: update example config

- misc/systemd/cgtproxy.service
> fix: disable ProtectControlGroups

- cmd/cgtproxy/cmd/error.go
- cmd/cgtproxy/cmd/root.go
- pkg/cgtproxy/core/core.go
- pkg/cgtproxy/core/error.go
- pkg/cgtproxy/core/run.go
> feat(core): add Stop

- cmd/cgtproxy/cmd/root.go
> chore: remove debug log

- internal/nftman/method.go
> fix: void add unused set

- cmd/cgtproxy/cmd/checkkernel.go
refer: https://stackoverflow.com/questions/39435927/what-is-oe-in-linux
> fix: correct /proc/modules checker

- docs/install.md
> docs: fix link

- docs/install.md
> docs: use bash to run get.sh

- go.mod
- go.sum
> build(deps): remove replace

- cmd/cgtproxy/cmd/check.go
- cmd/cgtproxy/cmd/checkconfig.go
- cmd/cgtproxy/cmd/checkkernel.go
- cmd/cgtproxy/cmd/checkpermission.go
- cmd/cgtproxy/cmd/consts.go
- cmd/cgtproxy/cmd/root.go
- docs/development.md
- docs/troubleshooting.md
- go.mod
- go.sum
- pkg/cgfsmon/public.go
- pkg/cgtproxy/private.go
- pkg/cgtproxy/public.go
- pkg/interfaces/cgmon.go
- pkg/interfaces/cgtproxy.go
- pkg/interfaces/routeman.go
- pkg/nftman/new.go
- pkg/nftman/private.go
- pkg/nftman/public.go
- pkg/routeman/private.go
- pkg/routeman/public.go
- chore: upgrade lib/go
- chore: update a error string
- feat(cmds/check): add --with-logger flag
- feat(cmd/check): run permission check
- chore: adjust command line output when exit with error
- fix(routeman): close channel after result send
- fix(routeman): return error in context when finish
- fix: add rules for ipv4/v6
- docs: add troubleshooting.md
- docs: update development.md
> prepare for v0.1.0

- misc/config/example.yaml
> chore: update example configuration

- .github/workflows/build-and-test.yaml
- Makefile
- cmd/cgtproxy/cmd/checkkernel.go
> build: fix arm build

- pkg/routeman/private.go
> fix(routeman): allow ipv6 rule fail

- go.mod
- go.sum
- pkg/interfaces/nftman.go
- pkg/nftman/connector/public.go
- pkg/nftman/lastingconnector/public.go
- pkg/nftman/new.go
- pkg/nftman/public.go
- pkg/routeman/private.go
- fix: report an error when the table already existed
- fix: release lasting netlink connection
> fix: release lasting netlink connection

- pkg/interfaces/nftman.go
> style: run go generate

- docs/troubleshooting.md
> docs: update troubleshooting.md

- pkg/cgfsmon/private.go
- pkg/nftman/private.go
- pkg/nftman/public.go
- style: reduce indent
- style: move method to private
> move to private

- pkg/cgfsmon/private.go
> style: reduce indent

- go.mod
- go.sum
- pkg/cgtproxy/config/config_test.go
- pkg/nftman/new.go
- pkg/nftman/nftman_test.go
- upgrade google/nftables as my PR is merged.
- upgrade test helper.
> refact: upgrade dependencies

- go.sum
- misc/systemd/cgtproxy.service
- pkg/cgtproxy/config/check.go
- pkg/nftman/private.go
- fix: enable ProtectControlGroups
- chore: go mod tidy
> use ro cgroup2 fs

- misc/config/example.yaml
> docs: update example configuration

- pkg/interfaces/nftman.go
- pkg/nftman/nftman_test.go
- pkg/nftman/public.go
- pkg/routeman/private.go
> refact(nftman)!: RemoveCgroups -> RemoveRoutes

- Makefile
> docs: remove some outdate comments in Makefile

- cmd/cgtproxy/cmd/root.go
> perf: enable lasting netlink socket by default

- docs/development.md
> docs: update development document

- docs/troubleshooting.md
- pkg/cgtproxy/config/consts.go
> chore: update default route-table value to 300

- pkg/cgfsmon/new.go
- pkg/nftman/public.go
- **perf: early return if no proxy or routes to add**
- **fix: adjust chan size try to avoid fs event drop**
> avoid event drop

- pkg/cgfsmon/new.go
> fix: adjust events buffer size to 1024

- cmd/cgtproxy/cmd/root.go
> chore: update --help

- misc/config/example.yaml
> chore: update example config

- .goreleaser.yaml
> ci: update goreleaser config

- .github/workflows/autotag.yaml
- .github/workflows/checks.yaml
- .github/workflows/prerelease.yaml
- .goreleaser.yaml
- Makefile
- cmd/cgtproxy/cmd/root.go
- scripts/get-project-version.sh
- scripts/print-variable.make
> feat: support --version

- .goreleaser.yaml
- scripts/get-project-version.sh
> ci: add missing v

- .github/workflows/autotag.yaml
> ci: add permissions to autotag

- .github/workflows/autotag.yaml
- Makefile
> ci: fetch tags for goreleaser

- Makefile
> chore: release 0.2.0

- scripts/get-project-version.sh
> refactor: rewrite scripts

- .github/workflows/checks.yaml
- Makefile
> build: rewrite Makefile

- cmd/cgtproxy/cmd/root.go
> chore: add a space in version output

- Makefile
> build: follow GNU code standard

- Makefile
- misc/config/example.yaml
> build: update Makefile

- .github/workflows/checks.yaml
> ci: enable checks on master push

- README.md
- docs/build.md
- docs/configuration.md
- docs/development.md
- docs/install.md
- **refactor: use environment variable to control buffer size**
- **docs: improve documentation readability and content**
> docs: improve documentation readability and content
